name: Repo B Workflow

on:
  repository_dispatch:
    types: [run-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build running"

  test-stage:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running test stage..."

          # simulate failure (change to 0 for success)
          exit 1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"
