name: Reusable Workflow

on:
  workflow_call:
    outputs:
      stage_result:
        value: ${{ jobs.test-stage.outputs.result }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build running"

  test-stage:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set.outputs.result }}
    steps:
      - id: set
        run: |
          echo "Running test stage..."

          # simulate failure
          echo "result=failure" >> $GITHUB_OUTPUT

          # IMPORTANT: don't fail job
          exit 0

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"
